import "./globals.css";
import { Manrope, Fraunces } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider"; 
import { Toaster } from "../components/ui/sonner";


export const metadata = {
  title: "CleverNote",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-body",
});

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-display",
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${manrope.variable} ${fraunces.variable} transition-colors duration-300`}
      >
      <Provider>
        {children}
      </Provider>  
      <Toaster />
      </body>
    </html>
    </ClerkProvider>
  );
}
